DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS skill CASCADE;
DROP TABLE IF EXISTS authority CASCADE;
DROP TABLE IF EXISTS post CASCADE;
DROP TABLE IF EXISTS project CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP SEQUENCE IF EXISTS user_seq CASCADE;