TRUNCATE TABLE "user" RESTART IDENTITY CASCADE;
TRUNCATE TABLE authority RESTART IDENTITY CASCADE;
TRUNCATE TABLE project RESTART IDENTITY CASCADE;
TRUNCATE TABLE skill RESTART IDENTITY CASCADE;
TRUNCATE TABLE role RESTART IDENTITY CASCADE;
TRUNCATE TABLE post RESTART IDENTITY CASCADE;

