server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fakng-db?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: postgres
    password: admin
  jpa:
    show-sql: true
    open-in-view: false
  properties:
    hibernate:
      format_sql: true
email:
  from: fakng-corporation@proton.me
aws:
  credentials:
    aws_access_key_id: AKIARFGG4ITCFBKUBC6X
    aws_secret_access_key: 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
  region: US_EAST_1
  s3:
    bucket: fakngcorporation
  ses:
    from: fakng-corporation@proton.me